/** User-facing paths consumed by the TanStack Router app and Amazi preview navigation. */
export const AMAZI_ROUTES = {
  account: "/account",
  accountSetupName: "/account/setup-name",
  admin: "/admin",
  adminAgentScenarios: "/admin/agent-scenarios",
  adminBookingRequests: "/admin/booking-requests",
  adminClient: "/admin/clients/:clientId",
  adminClients: "/admin/clients",
  adminDashboard: "/admin/dashboard",
  adminIntegrations: "/admin/integrations",
  adminKnowledgeBase: "/admin/knowledge-base",
  adminLogin: "/admin/login",
  adminRequest: "/admin/requests/:requestId",
  adminRequests: "/admin/requests",
  adminSettings: "/admin/settings",
  adminSiteLeads: "/admin/site-leads",
  adminSiteManagement: "/admin/site-management",
  adminSiteManagementAbout: "/admin/site-management/about",
  adminSiteManagementAllInclusive: "/admin/site-management/all-inclusive",
  adminSiteManagementBlog: "/admin/site-management/blog",
  adminSiteManagementCelebrations: "/admin/site-management/celebrations",
  adminSiteManagementEntertainment: "/admin/site-management/entertainment",
  adminSiteManagementGeneral: "/admin/site-management/general",
  adminSiteManagementHome: "/admin/site-management/home",
  adminSiteManagementNews: "/admin/site-management/news",
  adminSiteManagementOffers: "/admin/site-management/offers",
  adminSiteManagementRooms: "/admin/site-management/rooms",
  adminSiteManagementSection: "/admin/site-management/:sectionId",
  adminSiteManagementSpa: "/admin/site-management/spa",
  allInclusive: "/all-inclusive",
  about: "/about",
  blog: "/blog",
  celebrations: "/celebrations",
  entertainment: "/entertainment",
  hardwareProcedures: "/hardware-procedures",
  home: "/",
  login: "/login",
  news: "/news",
  offers: "/offers",
  privacy: "/privacy",
  rooms: "/rooms",
  spa: "/spa",
} as const;

/** Consolidated admin paths rendered by the dashboard page. */
export const AMAZI_ADMIN_DASHBOARD_ROUTES = [
  AMAZI_ROUTES.admin,
  AMAZI_ROUTES.adminAgentScenarios,
  AMAZI_ROUTES.adminBookingRequests,
  AMAZI_ROUTES.adminClients,
  AMAZI_ROUTES.adminClient,
  AMAZI_ROUTES.adminIntegrations,
  AMAZI_ROUTES.adminKnowledgeBase,
  AMAZI_ROUTES.adminRequests,
  AMAZI_ROUTES.adminRequest,
  AMAZI_ROUTES.adminSettings,
  AMAZI_ROUTES.adminSiteLeads,
  AMAZI_ROUTES.adminSiteManagementAbout,
  AMAZI_ROUTES.adminSiteManagementAllInclusive,
  AMAZI_ROUTES.adminSiteManagementBlog,
  AMAZI_ROUTES.adminSiteManagementCelebrations,
  AMAZI_ROUTES.adminSiteManagementEntertainment,
  AMAZI_ROUTES.adminSiteManagementGeneral,
  AMAZI_ROUTES.adminSiteManagementHome,
  AMAZI_ROUTES.adminSiteManagementNews,
  AMAZI_ROUTES.adminSiteManagementOffers,
  AMAZI_ROUTES.adminSiteManagementRooms,
  AMAZI_ROUTES.adminSiteManagementSection,
  AMAZI_ROUTES.adminSiteManagementSpa,
] as const;
