/** User-facing paths consumed by the TanStack Router app and Amazi preview navigation. */
export const ROUTES = {
  account: "/account",
  accountSetupName: "/account/setup-name",
  admin: "/admin",
  adminAgentScenarios: "/admin/agent-scenarios",
  adminBookingRequests: "/admin/booking-requests",
  adminClient: "/admin/clients/:clientId",
  adminClients: "/admin/clients",
  adminDashboard: "/admin/dashboard",
  adminIntegrations: "/admin/integrations",
  adminVoiceCalls: "/admin/voice-calls",
  adminVoiceAgentTest: "/admin/voice-agent-test",
  adminVoiceCall: "/admin/voice-calls/:callId",
  adminKnowledgeBase: "/admin/knowledge-base",
  adminLogin: "/admin/login",
  adminRequest: "/admin/requests/:requestId",
  adminRequests: "/admin/requests",
  adminSettings: "/admin/settings",
  adminServices: "/admin/services",
  adminSiteLeads: "/admin/site-leads",
  adminSiteManagement: "/admin/site-management",
  adminSiteManagementAbout: "/admin/site-management/about",
  adminSiteManagementAllInclusive: "/admin/site-management/all-inclusive",
  adminSiteManagementBlog: "/admin/site-management/blog",
  adminSiteManagementCelebrations: "/admin/site-management/celebrations",
  adminSiteManagementDocuments: "/admin/site-management/documents",
  adminSiteManagementFaq: "/admin/site-management/faq",
  adminSiteManagementEntertainment: "/admin/site-management/entertainment",
  adminSiteManagementGeneral: "/admin/site-management/general",
  adminSiteManagementHome: "/admin/site-management/home",
  adminSiteManagementNews: "/admin/site-management/news",
  adminSiteManagementOffers: "/admin/site-management/offers",
  adminSiteManagementRooms: "/admin/site-management/rooms",
  adminSiteManagementSection: "/admin/site-management/:sectionId",
  adminSiteManagementSpa: "/admin/site-management/spa",
  allInclusive: "/all-inclusive",
  about: "/about",
  blog: "/blog",
  booking: "/booking",
  bookingOld: "/booking-old",
  celebrations: "/celebrations",
  entertainment: "/entertainment",
  hardwareProcedures: "/hardware-procedures",
  home: "/",
  login: "/login",
  news: "/news",
  offers: "/offers",
  privacy: "/privacy",
  rooms: "/rooms",
  spa: "/spa",
  services: "/services",
  faq: "/faq",
} as const;

/** Consolidated admin paths rendered by the dashboard page. */
export const ADMIN_DASHBOARD_ROUTES = [
  ROUTES.admin,
  ROUTES.adminAgentScenarios,
  ROUTES.adminBookingRequests,
  ROUTES.adminClients,
  ROUTES.adminClient,
  ROUTES.adminIntegrations,
  ROUTES.adminVoiceCalls,
  ROUTES.adminVoiceAgentTest,
  ROUTES.adminVoiceCall,
  ROUTES.adminKnowledgeBase,
  ROUTES.adminRequests,
  ROUTES.adminRequest,
  ROUTES.adminSettings,
  ROUTES.adminSiteLeads,
  ROUTES.adminSiteManagementAbout,
  ROUTES.adminSiteManagementAllInclusive,
  ROUTES.adminSiteManagementBlog,
  ROUTES.adminSiteManagementCelebrations,
  ROUTES.adminSiteManagementDocuments,
  ROUTES.adminSiteManagementFaq,
  ROUTES.adminSiteManagementEntertainment,
  ROUTES.adminSiteManagementGeneral,
  ROUTES.adminSiteManagementHome,
  ROUTES.adminSiteManagementNews,
  ROUTES.adminSiteManagementOffers,
  ROUTES.adminSiteManagementRooms,
  ROUTES.adminSiteManagementSection,
  ROUTES.adminSiteManagementSpa,
] as const;
