CREATE TABLE "services" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(), "slug" TEXT NOT NULL, "name" TEXT NOT NULL,
  "description" TEXT, "status" TEXT NOT NULL DEFAULT 'draft', "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "services_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "services_slug_key" ON "services"("slug");
CREATE TABLE "service_variants" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(), "service_id" UUID NOT NULL, "name" TEXT NOT NULL, "description" TEXT,
  "price" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'RUB', "capacity" INTEGER NOT NULL,
  "duration_min" INTEGER, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "service_variants_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "service_variants_capacity_check" CHECK ("capacity" > 0), CONSTRAINT "service_variants_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE
);
CREATE INDEX "service_variants_service_id_active_idx" ON "service_variants"("service_id", "active");
CREATE TABLE "service_page_placements" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "service_id" UUID NOT NULL, "page_slug" TEXT NOT NULL, "position" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "service_page_placements_pkey" PRIMARY KEY ("id"), CONSTRAINT "service_page_placements_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "service_page_placements_service_id_page_slug_key" ON "service_page_placements"("service_id", "page_slug");
CREATE TABLE "service_availability_rules" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "service_id" UUID NOT NULL, "weekday" INTEGER NOT NULL, "start_time" TEXT NOT NULL, "end_time" TEXT NOT NULL, CONSTRAINT "service_availability_rules_pkey" PRIMARY KEY ("id"), CONSTRAINT "service_availability_rules_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE);
CREATE INDEX "service_availability_rules_service_id_weekday_idx" ON "service_availability_rules"("service_id", "weekday");
CREATE TABLE "service_schedule_blocks" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "service_id" UUID NOT NULL, "variant_id" UUID, "starts_at" TIMESTAMPTZ(3) NOT NULL, "ends_at" TIMESTAMPTZ(3) NOT NULL, "capacity" INTEGER NOT NULL, CONSTRAINT "service_schedule_blocks_pkey" PRIMARY KEY ("id"), CONSTRAINT "service_schedule_blocks_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE, CONSTRAINT "service_schedule_blocks_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "service_variants"("id") ON DELETE CASCADE);
CREATE INDEX "service_schedule_blocks_service_id_starts_at_idx" ON "service_schedule_blocks"("service_id", "starts_at");
CREATE TABLE "service_orders" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "user_id" UUID, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'new', "total" DECIMAL(12,2) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'RUB', "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "service_orders_pkey" PRIMARY KEY ("id"), CONSTRAINT "service_orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "guest_users"("id") ON DELETE SET NULL);
CREATE INDEX "service_orders_user_id_created_at_idx" ON "service_orders"("user_id", "created_at");
CREATE TABLE "service_order_items" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "order_id" UUID NOT NULL, "service_id" UUID NOT NULL, "variant_id" UUID NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "unit_price" DECIMAL(12,2) NOT NULL, CONSTRAINT "service_order_items_pkey" PRIMARY KEY ("id"), CONSTRAINT "service_order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "service_orders"("id") ON DELETE CASCADE, CONSTRAINT "service_order_items_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT, CONSTRAINT "service_order_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "service_variants"("id") ON DELETE RESTRICT);
CREATE TABLE "service_bookings" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "order_item_id" UUID NOT NULL, "service_id" UUID NOT NULL, "variant_id" UUID NOT NULL, "starts_at" TIMESTAMPTZ(3) NOT NULL, "ends_at" TIMESTAMPTZ(3) NOT NULL, "status" TEXT NOT NULL DEFAULT 'requested', "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "service_bookings_pkey" PRIMARY KEY ("id"), CONSTRAINT "service_bookings_order_item_id_key" UNIQUE ("order_item_id"), CONSTRAINT "service_bookings_order_item_id_fkey" FOREIGN KEY ("order_item_id") REFERENCES "service_order_items"("id") ON DELETE CASCADE, CONSTRAINT "service_bookings_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE RESTRICT, CONSTRAINT "service_bookings_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "service_variants"("id") ON DELETE RESTRICT);
CREATE INDEX "service_bookings_starts_at_status_idx" ON "service_bookings"("starts_at", "status");
CREATE TABLE "payment_attempts" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "order_id" UUID NOT NULL, "provider" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'not_started', "external_id" TEXT, "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "payment_attempts_pkey" PRIMARY KEY ("id"), CONSTRAINT "payment_attempts_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "service_orders"("id") ON DELETE CASCADE);
CREATE INDEX "payment_attempts_order_id_created_at_idx" ON "payment_attempts"("order_id", "created_at");
