/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pageLayoutRouteRouteImport } from './routes/(page-layout)/route'
import { Route as pageLayoutIndexRouteImport } from './routes/(page-layout)/index'

const pageLayoutRouteRoute = pageLayoutRouteRouteImport.update({
  id: '/(page-layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const pageLayoutIndexRoute = pageLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pageLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof pageLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof pageLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(page-layout)': typeof pageLayoutRouteRouteWithChildren
  '/(page-layout)/': typeof pageLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(page-layout)' | '/(page-layout)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  pageLayoutRouteRoute: typeof pageLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(page-layout)': {
      id: '/(page-layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pageLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page-layout)/': {
      id: '/(page-layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pageLayoutIndexRouteImport
      parentRoute: typeof pageLayoutRouteRoute
    }
  }
}

interface pageLayoutRouteRouteChildren {
  pageLayoutIndexRoute: typeof pageLayoutIndexRoute
}

const pageLayoutRouteRouteChildren: pageLayoutRouteRouteChildren = {
  pageLayoutIndexRoute: pageLayoutIndexRoute,
}

const pageLayoutRouteRouteWithChildren = pageLayoutRouteRoute._addFileChildren(
  pageLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  pageLayoutRouteRoute: pageLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
